language: java
notifications: 
   slack: 
      secure: FIHlTn/YO7Wgumm1uIqmoEsqjQA7fV0AE94Rjc5yKzM3AquQa8HicgDVVk0d2GrKRnl0xt3j4ZJV//VJyIjlCd/QVKuj48R2ChjEY2im3+99HFPafCUI5/S2uyowKU6mJTFonH9v6p41eqxdbiAxJdDGOT0V2Gpt3UBSNuHz8ED9/aIHqv+P7M+VD6Xd2XYwctPniWlaSWx57sWcnG/VkFG45qFQAyha64uxOOe4M3ZmG/n5FfauZ8cBVLiRKEIr+CyNhh1ujfzi7+4uzMlSNL5t/BbZamAQuZzqGzGQ9RVvIlyPgUGNJtDEE/hWS09aagXF5T6EMj00szizErh4J1/x4qZwml5+TcBN31E0QmAhCtZe85sr3tYgic+hEz9XX1yymQzf/C7n4to2yNvq0r4g51xDk8IuP95WEh7zaqLlvFZvBFgxpHZBMYlRvhytjOYDeIFRMcGwHZcXosaG2ejqDwcGq/LC4oeG4sSwmg9sdRrtcmcanrNqrBka86WYO6LntI3JdZ86/1ACEUHzhCCwvrKELc9Ji1xxGAgS7QKH+s2/hnJuiMyv73gOVLKYC+wPMLt+fvOmPLSEl+PJiAIlToBq1KUBg03RSQLfPOLD7OrJ8VvDZsEPwejqlGDyc4wRglS9OTi7SnN5LYHSDNDdGdREegWqq9qDHEYEVLI=
env: 
   global: 
   - MODULE_ID=cbstreams
   - TARGET_VERSION=1.1.0
   matrix: 
   - ENGINE=lucee@5
   - ENGINE=lucee@45
   - ENGINE=adobe@2018
   - ENGINE=adobe@2016
   - ENGINE=adobe@11
branches: 
   only: 
   - development
   - master
dist: trusty
sudo: required
before_install: 
- sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
- sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
install: 
- sudo apt-get update && sudo apt-get --assume-yes install rsync jq commandbox
- box install commandbox-cfconfig,commandbox-dotenv,commandbox-docbox
- box config set endpoints.forgebox.APIToken=$FORGEBOX_API_TOKEN > /dev/null
- mkdir test-harness/tests/results
script: 
- cd test-harness
- box install
- box server start serverConfigFile="server-${ENGINE}.json"
- curl http://localhost:60299
- cd $TRAVIS_BUILD_DIR
- box task run taskfile=build/Build target=run :version=${TARGET_VERSION} :projectName=${MODULE_ID} :buildID=${TRAVIS_BUILD_NUMBER}
   :branch=${TRAVIS_BRANCH}
after_failure: 
- cd $TRAVIS_BUILD_DIR/test-harness
- box server log name=${ENGINE}
- cat `box system-log`
deploy: 
-  provider: s3
   on: 
      branch: 
      - master
      - development
      condition: $ENGINE = lucee@45
   skip_cleanup: true
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_ACCESS_SECRET
   bucket: downloads.ortussolutions.com
   local-dir: $TRAVIS_BUILD_DIR/.artifacts/$MODULE_ID
   upload-dir: ortussolutions/coldbox-modules/$MODULE_ID
   acl: public_read
-  provider: s3
   on: 
      branch: 
      - master
      - development
      condition: $ENGINE = lucee@45
   skip_cleanup: true
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_ACCESS_SECRET
   bucket: apidocs.ortussolutions.com
   local-dir: $TRAVIS_BUILD_DIR/.tmp/apidocs
   upload-dir: coldbox-modules/$MODULE_ID/$TARGET_VERSION
   acl: public_read
after_deploy: 
- cd ${TRAVIS_BUILD_DIR}/.tmp/${MODULE_ID}
- if [ ${ENGINE} = 'lucee@45' ]; then box forgebox publish; fi
